@startuml
skinparam componentStyle rectangle
[espi_mem_read_dev_0]-->[espi_mem_read_common]
[espi_mem_read_dev_1]-->[espi_mem_read_common]
[espi_mem_read_common]-->[espi_mem_read_align]

[espi_mem_wriet_dev_0]-->[espi_mem_write_common]
[espi_mem_write_dev_1]-->[espi_mem_write_common]
[espi_mem_write_common]-->[espi_mem_write_align]
@enduml
@startuml
skinparam componentStyle rectangle
left to right direction
[espi_io_read_dev_0]-->[espi_io_read_common]
[espi_io_read_dev_1]-->[espi_io_read_common]
[espi_io_write_dev_0]-->[espi_io_write_common]
[espi_io_write_dev_1]-->[espi_io_write_common]
[espi_fixed_io_read]-->[espi_fixed_io_read_common]
[espi_fixed_io_write]-->[espi_fixed_io_write_common]
[espi_conf_io_read_dev]-->[espi_io_read_common]
[espi_conf_io_write_dev]-->[espi_io_write_common]
[espi_legacy_com_io_read]-->[espi_io_read_common]
[espi_legacy_com_io_read]-->[uart_srv_legacy_com_read]
[espi_legacy_com_io_write]-->[espi_io_write_common]
[espi_legacy_com_io_write]-->[uart_srv_legacy_com_write]
[espi_fixed_io_read_common]->[espi_fixed_io_read_shadow]
[espi_fixed_io_read_common]-->[espi_io_read_common]
[espi_fixed_io_write_common]->[espi_fixed_io_write_shadow]
[espi_fixed_io_write_common]-->[espi_io_write_common]
@enduml
